version: "3.9"

services:
  db:
    image: postgres:15
    container_name: toyland_db
    ports:
      - "20260:5432"   # PostgreSQL port ของตัวเอง
    environment:
      POSTGRES_USER: toyuser
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: toyland_db
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U toyuser"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  backend:
    build: ./backend
    container_name: toyland_backend
    ports:
      - "30260:8000"   # Django dev server ตัวเอง
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=toyland_db
      - DB_USER=toyuser
      - DB_PASSWORD=1234
    command: >
      sh -c "until nc -z db 5432; do echo 'Waiting for PostgreSQL...'; sleep 2; done &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  frontend:
    build: ./frontend
    container_name: toyland_frontend
    ports:
      - "10260:10260"   # React dev server main entry
    stdin_open: true
    tty: true
    command: npm start   # รัน react-scripts start

volumes:
  db_data:
