# Generated by Django 5.1.2 on 2025-02-11 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_message_chat_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatroom",
            options={"verbose_name": "Chat Room", "verbose_name_plural": "Chat Rooms"},
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
            },
        ),
        migrations.RenameField(
            model_name="message",
            old_name="chat_id",
            new_name="chat_room",
        ),
    ]
