# Generated by Django 5.1.2 on 2025-01-29 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mycollections", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collection",
            name="status",
        ),
    ]
