# Generated by Django 5.1.2 on 2025-01-31 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mycollections", "0002_remove_collection_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="is_shared",
            field=models.BooleanField(default=False),
        ),
    ]
