# Generated by Django 5.1.2 on 2024-12-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0002_remove_post_user_name_post_user_customuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
