# Generated by Django 5.1.2 on 2025-02-03 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "community",
            "0006_alter_customuser_options_alter_customuser_managers_and_more",
        ),
    ]

    operations = []
