# Generated by Django 5.1.6 on 2025-03-12 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_alter_like_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
